/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import controller.ItemJpaController;
import entity.Area;
import entity.Autor;
import entity.CasaPub;
import entity.Colecoes;
import entity.Editora;
import entity.Genero;
import entity.Item;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Point;
import java.util.Date;
import javax.persistence.Persistence;
/**
 *
 * @author Pc
 */
public class FrmCadItem extends javax.swing.JFrame {
    
    public char tipoItem = '1';

    /**
     * Creates new form FrmCadItem
     */
    public FrmCadItem() {
        
        initComponents();
        setLocationRelativeTo(null); 
        txtTitulo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btgIdioma = new javax.swing.ButtonGroup();
        btgLegenda = new javax.swing.ButtonGroup();
        btgCondicao = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaObs = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        pnlIdioma = new javax.swing.JPanel();
        rdbPortugues = new javax.swing.JRadioButton();
        rdbIngles = new javax.swing.JRadioButton();
        rdbLegEspanhol = new javax.swing.JRadioButton();
        rdbLegIngles = new javax.swing.JRadioButton();
        rdbLegPortugues = new javax.swing.JRadioButton();
        rdbEspanhol = new javax.swing.JRadioButton();
        rdbLegenda = new javax.swing.JRadioButton();
        txtLocal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTipoItem = new javax.swing.JLabel();
        lblCad = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblCasaPub = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        lblCol = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        rdbNovo = new javax.swing.JRadioButton();
        rdbDesgastado = new javax.swing.JRadioButton();
        rdbUsado = new javax.swing.JRadioButton();
        rdbVelho = new javax.swing.JRadioButton();
        lblIdioma = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbmCol = new javax.swing.JComboBox();
        spnVolume = new javax.swing.JSpinner();
        btnAddGenero = new javax.swing.JButton();
        btnAddArea = new javax.swing.JButton();
        btnAddAutor = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        spnPaginas = new javax.swing.JSpinner();
        btnOg = new javax.swing.JButton();
        btnAddCasaPub = new javax.swing.JButton();
        btnMudar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        cmbGenero = new javax.swing.JComboBox();
        cmbCasaPub = new javax.swing.JComboBox();
        cmbEditora = new javax.swing.JComboBox();
        cmbAutor = new javax.swing.JComboBox();
        cmbArea = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setOpaque(false);

        txaObs.setColumns(20);
        txaObs.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        txaObs.setRows(5);
        jScrollPane1.setViewportView(txaObs);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.ipady = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 33, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel9.setText("Observação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        pnlIdioma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlIdioma.setMaximumSize(new java.awt.Dimension(320, 103));
        pnlIdioma.setMinimumSize(new java.awt.Dimension(320, 103));
        pnlIdioma.setOpaque(false);

        btgIdioma.add(rdbPortugues);
        rdbPortugues.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbPortugues.setSelected(true);
        rdbPortugues.setText("Portugues");
        rdbPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPortuguesActionPerformed(evt);
            }
        });

        btgIdioma.add(rdbIngles);
        rdbIngles.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbIngles.setText("Inglês");
        rdbIngles.setEnabled(false);

        btgLegenda.add(rdbLegEspanhol);
        rdbLegEspanhol.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbLegEspanhol.setText("Espanhol");
        rdbLegEspanhol.setEnabled(false);

        btgLegenda.add(rdbLegIngles);
        rdbLegIngles.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbLegIngles.setText("Inglês");
        rdbLegIngles.setEnabled(false);

        btgLegenda.add(rdbLegPortugues);
        rdbLegPortugues.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbLegPortugues.setText("Portugues");
        rdbLegPortugues.setEnabled(false);

        btgIdioma.add(rdbEspanhol);
        rdbEspanhol.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbEspanhol.setText("Espanhol");
        rdbEspanhol.setEnabled(false);

        rdbLegenda.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbLegenda.setText("Legenda");

        javax.swing.GroupLayout pnlIdiomaLayout = new javax.swing.GroupLayout(pnlIdioma);
        pnlIdioma.setLayout(pnlIdiomaLayout);
        pnlIdiomaLayout.setHorizontalGroup(
            pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdiomaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIdiomaLayout.createSequentialGroup()
                        .addComponent(rdbLegPortugues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbLegIngles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbLegEspanhol))
                    .addGroup(pnlIdiomaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rdbPortugues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbIngles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbEspanhol)))
                .addGap(73, 73, 73))
            .addGroup(pnlIdiomaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbLegenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIdiomaLayout.setVerticalGroup(
            pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdiomaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPortugues)
                    .addComponent(rdbIngles)
                    .addComponent(rdbEspanhol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbLegenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbLegPortugues)
                    .addComponent(rdbLegIngles)
                    .addComponent(rdbLegEspanhol))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 33, 0, 0);
        getContentPane().add(pnlIdioma, gridBagConstraints);

        txtLocal.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        txtLocal.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        getContentPane().add(txtLocal, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel11.setText("Localização:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 100, 0, 0);
        getContentPane().add(jLabel11, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel8.setText("Edição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 134, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        txtEdi.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        txtEdi.setOpaque(false);
        txtEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        getContentPane().add(txtEdi, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel6.setText("Ano:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 150, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel13.setText("Volume:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 126, 0, 0);
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel10.setText("Paginas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 126, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        lblArea.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblArea.setText("Area:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 112, 0, 0);
        getContentPane().add(lblArea, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblTitulo.setText("Titulo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 105, 0, 0);
        getContentPane().add(lblTitulo, gridBagConstraints);

        lblTipoItem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTipoItem.setText("________");
        lblTipoItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTipoItemMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 0, 0);
        getContentPane().add(lblTipoItem, gridBagConstraints);

        lblCad.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCad.setText("Cadastro de ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 29, 0, 0);
        getContentPane().add(lblCad, gridBagConstraints);

        lblGenero.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblGenero.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 95, 0, 0);
        getContentPane().add(lblGenero, gridBagConstraints);

        lblAutor.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblAutor.setText("Autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 105, 0, 0);
        getContentPane().add(lblAutor, gridBagConstraints);

        lblCasaPub.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblCasaPub.setText("Casa Publicadora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 63, 0, 0);
        getContentPane().add(lblCasaPub, gridBagConstraints);

        lblEditora.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblEditora.setText("Editora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 96, 0, 0);
        getContentPane().add(lblEditora, gridBagConstraints);

        txtAno.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        txtAno.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        getContentPane().add(txtAno, gridBagConstraints);

        lblCol.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblCol.setText("Coleção:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 91, 0, 0);
        getContentPane().add(lblCol, gridBagConstraints);

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setOpaque(false);

        btgCondicao.add(rdbNovo);
        rdbNovo.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbNovo.setText("Novo");

        btgCondicao.add(rdbDesgastado);
        rdbDesgastado.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbDesgastado.setText("Desgastado");

        btgCondicao.add(rdbUsado);
        rdbUsado.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbUsado.setText("Usado");

        btgCondicao.add(rdbVelho);
        rdbVelho.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        rdbVelho.setText("Velho");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbDesgastado)
                    .addComponent(rdbNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbUsado)
                    .addComponent(rdbVelho))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbNovo)
                    .addComponent(rdbUsado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbDesgastado)
                    .addComponent(rdbVelho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 18, 0, 0);
        getContentPane().add(jPanel14, gridBagConstraints);

        lblIdioma.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        lblIdioma.setText("Idioma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 97, 0, 0);
        getContentPane().add(lblIdioma, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        jLabel5.setText("Condição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 115, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        cbmCol.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        cbmCol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbmCol.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 33, 0, 0);
        getContentPane().add(cbmCol, gridBagConstraints);

        spnVolume.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        spnVolume.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(spnVolume, gridBagConstraints);

        btnAddGenero.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnAddGenero.setText("+");
        btnAddGenero.setOpaque(false);
        btnAddGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGeneroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(btnAddGenero, gridBagConstraints);

        btnAddArea.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnAddArea.setText("+");
        btnAddArea.setOpaque(false);
        btnAddArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(btnAddArea, gridBagConstraints);

        btnAddAutor.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnAddAutor.setText("+");
        btnAddAutor.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(btnAddAutor, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jButton4.setText("+");
        jButton4.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(jButton4, gridBagConstraints);

        spnPaginas.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        spnPaginas.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 141;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 18, 0, 0);
        getContentPane().add(spnPaginas, gridBagConstraints);

        btnOg.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        btnOg.setText("OK");
        btnOg.setOpaque(false);
        btnOg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 49, 0, 0);
        getContentPane().add(btnOg, gridBagConstraints);

        btnAddCasaPub.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnAddCasaPub.setText("+");
        btnAddCasaPub.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(btnAddCasaPub, gridBagConstraints);

        btnMudar.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        btnMudar.setText("Mudar");
        btnMudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 28, 0, 0);
        getContentPane().add(btnMudar, gridBagConstraints);

        txtTitulo.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 33, 0, 0);
        getContentPane().add(txtTitulo, gridBagConstraints);

        cmbGenero.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGenero.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 33, 0, 0);
        getContentPane().add(cmbGenero, gridBagConstraints);

        cmbCasaPub.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        cmbCasaPub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCasaPub.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        getContentPane().add(cmbCasaPub, gridBagConstraints);

        cmbEditora.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        cmbEditora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEditora.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 33, 0, 0);
        getContentPane().add(cmbEditora, gridBagConstraints);

        cmbAutor.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAutor.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 33, 0, 0);
        getContentPane().add(cmbAutor, gridBagConstraints);

        cmbArea.setEditable(true);
        cmbArea.setFont(new java.awt.Font("Andalus", 0, 16)); // NOI18N
        cmbArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Abobora", "Kakitos", "Melancia", "Lodaica" }));
        cmbArea.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 33, 0, 0);
        getContentPane().add(cmbArea, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTipoItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTipoItemMouseEntered
    }//GEN-LAST:event_lblTipoItemMouseEntered

    private void rdbPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPortuguesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbPortuguesActionPerformed

    private void txtEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdiActionPerformed

    }//GEN-LAST:event_txtEdiActionPerformed

    private void btnOgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgActionPerformed
        Date date = new Date();
        String idioma = "";
        String legenda = "";
        int condicao = 0;
        Item item = new Item();
        

        ItemJpaController cont = new ItemJpaController(Persistence.createEntityManagerFactory("tccBibliotecaPU"));

        

        //Idioma e Lengenda
        if(rdbPortugues.isSelected()){
            idioma = "Português";
        }
        if(rdbIngles.isSelected()){
            idioma = "Inglês";
        }
        if(rdbEspanhol.isSelected()){
            idioma = "Espanhol";
        }

        if(!rdbLegenda.isSelected()){
            legenda = "";
        }
        if(rdbLegPortugues.isSelected()){
            legenda = "Portugês";
        }if(rdbLegIngles.isSelected()){
            legenda = "Inglês";
        }if(rdbLegEspanhol.isSelected()){
            legenda = "Espanhol";
        }

        //Condição
        if(rdbNovo.isSelected()){
            condicao = 1;
        }if(rdbUsado.isSelected()){
            condicao = 2;
        }if(rdbDesgastado.isSelected()){
            condicao = 3;
        }if(rdbVelho.isSelected()){
            condicao = 4;
        }

        //Declara Chave Primaria
        int areaInt = cmbArea.getSelectedIndex();
        int generoInt = cmbGenero.getSelectedIndex();
        int autorInt = cmbAutor.getSelectedIndex();
        int colecaoInt = cbmCol.getSelectedIndex();
        int casaInt = cmbCasaPub.getSelectedIndex();
        int editoraInt = cmbEditora.getSelectedIndex();

        //Declara Objetos
        Area area = new Area(areaInt);
        Genero genero = new Genero(generoInt);
        Autor autor = new Autor(autorInt);
        Colecoes col = new Colecoes(colecaoInt);
        CasaPub casa = new CasaPub(casaInt);
        Editora editora = new Editora(editoraInt);

        //Set cont to item
        item.setAnoItem(Integer.parseInt(txtAno.getText()));
        item.setAreaItem(area);
        item.setTituloItem(txtTitulo.getText());
        item.setGeneroItem(genero);
        item.setObsItem(txaObs.getText());
        item.setIdiomaItem(idioma);
        item.setCondicaoItem(condicao);
        item.setAutorItem(autor);
        item.setDataAquisicaoitem(date);
        item.setLegendaItem(legenda);
        item.setEdicaoItem(Integer.parseInt(txtEdi.getText()));
        item.setColecaoItem(col);
        item.setCasaPubitem(casa);
        item.setVolumeAtualitem((Integer) spnVolume.getValue());
        item.setPaginasItem((Integer) spnPaginas.getValue());
        item.setLocalizacaoItem(txtLocal.getText());
        item.setEditoraItem(editora);

    }//GEN-LAST:event_btnOgActionPerformed

    private void btnAddAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAreaActionPerformed

    }//GEN-LAST:event_btnAddAreaActionPerformed

    private void btnAddGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGeneroActionPerformed

    }//GEN-LAST:event_btnAddGeneroActionPerformed

    private void btnMudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMudarActionPerformed
        switch(tipoItem){
            case('1'):
                ficha();
                
            break;
            case('2'):
                dvd();
                break;
                
            case('3'):
                allConponentsVisible(true);
                tipoItem = '1';
                break;
        }
        
        
        
    }//GEN-LAST:event_btnMudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCondicao;
    private javax.swing.ButtonGroup btgIdioma;
    private javax.swing.ButtonGroup btgLegenda;
    private javax.swing.JButton btnAddArea;
    private javax.swing.JButton btnAddAutor;
    private javax.swing.JButton btnAddCasaPub;
    private javax.swing.JButton btnAddGenero;
    private javax.swing.JButton btnMudar;
    private javax.swing.JButton btnOg;
    private javax.swing.JComboBox cbmCol;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JComboBox cmbAutor;
    private javax.swing.JComboBox cmbCasaPub;
    private javax.swing.JComboBox cmbEditora;
    private javax.swing.JComboBox cmbGenero;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCad;
    private javax.swing.JLabel lblCasaPub;
    private javax.swing.JLabel lblCol;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblTipoItem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlIdioma;
    private javax.swing.JRadioButton rdbDesgastado;
    private javax.swing.JRadioButton rdbEspanhol;
    private javax.swing.JRadioButton rdbIngles;
    private javax.swing.JRadioButton rdbLegEspanhol;
    private javax.swing.JRadioButton rdbLegIngles;
    private javax.swing.JRadioButton rdbLegPortugues;
    private javax.swing.JRadioButton rdbLegenda;
    private javax.swing.JRadioButton rdbNovo;
    private javax.swing.JRadioButton rdbPortugues;
    private javax.swing.JRadioButton rdbUsado;
    private javax.swing.JRadioButton rdbVelho;
    private javax.swing.JSpinner spnPaginas;
    private javax.swing.JSpinner spnVolume;
    private javax.swing.JTextArea txaObs;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtEdi;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    
    //Ultilitarios
    private void componentVisible(Component container, Boolean hab) {
        
            container.setVisible(hab);
            this.revalidate();
        }
    
    private void allConponentsVisible(Boolean hab){
        Component[] components = this.getContentPane().getComponents();
        
        for(Component c : components){
        c.setVisible(hab);
        }
    }
    
    //Tipos Formulario
    
    private void ficha(){
        allConponentsVisible(false);
                componentVisible(lblArea, true);
                componentVisible(cmbArea, true);
                componentVisible(pnlIdioma, true);
                componentVisible(lblIdioma, true);
                componentVisible(lblTitulo, true);
                componentVisible(txtTitulo, true);
                componentVisible(lblGenero, true);
                componentVisible(cmbGenero, true);
                componentVisible(btnMudar, true);
                componentVisible(btnOg, true);
                componentVisible(lblCad, true);
                componentVisible(lblTipoItem, true);
               
                lblTipoItem.setText("Folheto");
                tipoItem = '2';
                this.pack();
                this.revalidate();
    }
    
    private void dvd(){
        
        componentVisible(lblArea, true);
                componentVisible(cmbArea, true);
                componentVisible(pnlIdioma, true);
                componentVisible(lblIdioma, true);
                componentVisible(lblTitulo, true);
                componentVisible(txtTitulo, true);
                componentVisible(lblGenero, true);
                componentVisible(cmbGenero, true);
                componentVisible(btnMudar, true);
                componentVisible(btnOg, true);
                componentVisible(lblCad, true);
                componentVisible(lblTipoItem, true);
                componentVisible(cmbEditora, true);
                componentVisible(lblEditora, true);
                componentVisible(cbmCol, true);
                componentVisible(lblCol, true);
                GridBagConstraints cCbm = new GridBagConstraints();
                GridBagConstraints cLbl = new GridBagConstraints();
                cLbl.gridx = 0;
                cCbm.gridx = 1;
                
                this.pack();
                this.revalidate();
                
    }
    
}

